version: "3"

services:
  libretranslate:
    container_name: libretranslate
    image: libretranslate/libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - LT_API_UPDATE_MODELS=true

