server:
  port: 8080

spring:
  application:
    name: jpn-text-analyzer

  servlet:
    multipart:
      max-file-size: 10MB  # Максимальный размер одного загружаемого файла
      max-request-size: 15MB  # Максимальный общий размер загрузки (всех файлов в одном запросе)
      file-size-threshold: 2KB  # Размер файла, после которого он должен быть записан на диск



springdoc:
  swagger-ui:
    url: /v3/api-docs
    disable-swagger-default-url: false
    path: /swagger-ui.html
    enabled: true
    api-docs:
      path: /v3/api-docs
      versions:
        openapi_3.0: OpenAPI 3.0

pictureSearchUrl: "https://duckduckgo.com/?q=$query&iar=images&iax=images&ia=images&p=1"


