server:
  port: 8080

spring:
  application:
    name: translate-helper
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 120000
          libretranslate-client:
            connectTimeout: 5000
            readTimeout: 120000
feign:
  client:
    libretranslate-client:
      url: http://127.0.0.1:5000

pictureSearchUrl: "https://duckduckgo.com/?q=$query&iar=images&iax=images&ia=images"


